# n
VAR attribute = ""
"HEY FELLER....... YOU'VE BEEN IN A CAR CRASH. PRESS ENTER IF YOU LIKE WHAT YOU HEAR."
->next1
==next1
"I'M SORRY TO ALARM YOU.. BUT YOU'RE IN A VIDEO GAME NOW. YOUR 'ENERGY' IS LIMITED ARBITRARILY."
->next2
==next2
"LUCKILY FOR YOU, YOU'RE <b>{attribute}</b>!"
->END